apiVersion: skaffold/v1beta15
kind: Config
build:
  tagPolicy:
    sha256: {}
  # defines where to find the code at build time and where to push the resulting image
  artifacts:
  - image: gcr.io/developer-269501/k8s-with-google-storage/nfs-bucket-server
    context: microservices/nfs-bucket-server
  - image: gcr.io/developer-269501/k8s-with-google-storage/backend
    context: microservices/backend
# defines the Kubernetes manifests to deploy on each run
deploy:
  kubectl:
    manifests:
    - ./kubernetes/nfs-bucket/*.yaml
    - ./kubernetes/backend/*.yaml
profiles:
# use the cloudbuild profile to build images using Google Cloud Build
- name: cloudbuild
  build:
    googleCloudBuild: {}